{
 "title": "Exam",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Free memory metrics",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemFree_bytes)"
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (node_cpu_seconds_total)"
    }
   ]
  },
  {
   "title": "Docker containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}